### ISSUE TITLE
channel_alias support for constructor

### ISSUE THREAD

**Issue by alep** [conda/constructor#147]
Calling `constructor ./` with the following file will fail because constructor doesn't support channel_alias. 

The problem seems points to this https://github.com/conda/constructor/blob/master/constructor/fcp.py#L256-L258

```yaml
name: "test"
version: 0.1.0
channels:
    - conda-forge
specs:
    - python
keep_pkgs: true
```
