### ISSUE TITLE
Unable to get full package URL to work

### ISSUE THREAD

**Issue by jakirkham** [conda/constructor#161]
Not totally sure the right way to do this as the examples are a bit unclear to me on this point. However tried to create an installer like this where very specific `packages` are used to fulfill the `specs`. However the latest `constructor` errors out on on this. Am I doing this incorrectly? How should I be writing the `construct.yaml` file to lock down the packages used?

```yaml
name: "test"
version: 0.1.0
channels:
  - https://conda.anaconda.org/anaconda/
specs:
  - zlib
packages:
  - https://conda.anaconda.org/anaconda/osx-64/zlib-1.2.11-hf3cbc9b_2.tar.bz2#f77c7d05dc47868e181135af65cb6e26
```
