### ISSUE TITLE
conda-forge packages missing after installing

### ISSUE THREAD

**Issue by foxBMS** [conda/constructor#210]
We are building a miniconda installer with constructor under Windows7 (details below). And at first sight it looks like everything works as expected:
- building the installer with no errors/warnings
- running the installer with no errors/warnings (both, cmd and GUI)
- `conda list` works like a charm, and tells all packages listed in `constructor.yml` are there (pure python packages and also pure binary packages).
- `where doxygen` returns `doxygen.exe` where it should be etc. This works for all *.exe that are installed, so no problems here.
- `python -c "import alabaster"` fails, and tells the `ModuleNotFoundError` error. And that after `conda list` told me 20seconds before it is available.
- And of course, doing a `conda install alabaster` installs `alabaster`, succeeds, and `alabaster` is then importable.

**This happens for ALL python packages in that constructed installer that are from `conda-forge` and not from anaconda/continuum channel.** And again, the binaries, like e.g., `doxygen.exe` from `conda-forge`  are not missing and are found as expected.
This behavior happens as well locally as on a new build machine.

What is causing unexpected behavior? Is there a some workaround?

Not sure, but the problems seems to be cross-platform, as #201 seems to have the same problem in Linux/Unix.

---

`constructor.yml`:
```yml
name: foxconda
version: 1.1.1-devel

install_in_dependency_order: True

channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2    # [win]
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/foxbms

write_condarc: True

keep_pkgs: True

specs:
  - python 3.*
  - conda
  - conda-build
  - console_shortcut
  - menuinst
  - doxygen
  - graphviz
  - alabaster
  - appdirs
  - breathe
  - git
  - pycosat
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib
  - sphinxcontrib-websupport
  - gcc-arm-none-eabi

license_file: EULA.txt

# Welcome image for Windows installer
welcome_image: welcome_image.png   # [win]
header_image: header_image.png     # [win]
icon_image: icon_image.png         # [win]
```

`ver`:
```cmd
Microsoft Windows [Version 6.1.7601]
```

`constructor -V`:
```
constructor version: 2.1.1
```

`conda info`:
```cmd
(base) C:\Users\dev>conda info

     active environment : base
    active env location : D:\conda-devel\miniconda3
            shell level : 1
       user config file : C:\Users\dev\.condarc
 populated config files : C:\Users\dev\.condarc
          conda version : 4.5.8
    conda-build version : 3.10.9
         python version : 3.6.6.final.0
       base environment : D:\conda-devel\miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : D:\conda-devel\miniconda3\pkgs
                          C:\Users\dev\AppData\Local\conda\conda\pkgs
       envs directories : D:\conda-devel\miniconda3\envs
                          C:\Users\dev\AppData\Local\conda\conda\envs
                          C:\Users\dev\.conda\envs
               platform : win-64
             user-agent : conda/4.5.8 requests/2.19.1 CPython/3.6.6 Windows/7 Windows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False
```
