### ISSUE TITLE
Problems with Qt5 and Numpy DLLs

### ISSUE THREAD

**Issue by bburan** [conda/constructor#223]
I created an installer using conda constructor. However, when I tested it on Windows 7 (64 bit), it does not appear to be updating the system path properly. For example, when I try to run my application (e.g., `abr_gui.exe`), it fails and exits since it's unable to load Numpy and/or Qt5 DLLs. When I test via python.exe:

    import numpy

or

    from enaml import qt

Both fail due to DLL issues. However, when I manually append `%INSTALLDIR%\Library\bin` to the system path, everything works. Am I doing something wrong?

For details, I created the package using this `meta.yaml`:
```
{% set name = "abr" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: '../abr' 
   
build:

  entry_points:
    - abr_gui = abr.app.cmd_main:main
    - abr_loop = abr.app.cmd_main_loop:main

requirements:
  host:
    - python
    - setuptools
  run:
    - python >=3.6
    - matplotlib >=3.0.0
    - scipy
    - numpy
    - enaml
    - pandas
    - pytables

test:
  imports:
    - abr
    - abr.app
    - abr.data
    - abr.parsers
  commands:
    - abr_gui

about:
  home: https://github.com/bburan/abr
  license: BSD 3-clause
  license_family: BSD
  summary: GUI application for analyzing ABR waveforms

extra:
  recipe-maintainers:
    - bburan
```
and tried to create an installer using this `construct.yaml`:

    name: ABR-analysis
    version: 0.0.1

    channels:
        - file:///c:/users/bburan/Anaconda3/conda-bld
        - http://repo.anaconda.com/pkgs/main
        - http://repo.anaconda.com/pkgs/msys2

    specs:
        - abr
