### ISSUE TITLE
Allow for the creation of multiple environments with custom names

### ISSUE THREAD

**Issue by goanpeca** [conda/constructor#359]
Would it be possible to update constructor to do something like this:

```yaml
name: Uberconda
version: 1.0
install_in_dependency_order: True
channels:
  - http://repo.anaconda.com/pkgs/main/

specs:
    - python 3.5*
    - conda

envs:
  - name: something_else
    specs:
    - python 3.5*
    - numpy
  - name: _something_private
    specs:
    - python 3.5*
    - pandas

license_file: EULA.txt

# Welcome image for Windows installer
welcome_image: bird.png                  [win]
```
