### ISSUE TITLE
noarch-only repositories cause constructor to crash

### ISSUE THREAD

**Issue by FaustinCarter** [conda/constructor#408]
If a repository in `channels` contains only a noarch folder, and not a folder specific to the platform architecture targeted for the installer build, constructor crashes because it can't find a `repodata.json` file for the target architecture.

As a minimal example, take the following `construct.yml`, in which I specify a required package called `some-noarch-package` that is hosted at https://myhost.com/noarchrepo.

``` yaml
channels:
 - https://conda.anaconda.org/conda-forge
 - https://myhost.com/noarchrepo

specs:
 - some-noarch-package

installer_type: osx-64
```

Constructor will now try to open `repodata.json` files located at
 - https://myhost.com/noarchrepo/osx-64/repodata.json (This will 404)
 - https://myhost.com/noarchrepo/noarch/repodata.json (This will be fine, and will contain `some-noarch-package`)

The specific place in the code where this fails is here: https://github.com/conda/constructor/blob/47d61a2f6924e36c27197be94605e724c006055e/constructor/preconda.py#L37-L40

I maintain that the 404 error on the platform-specific repo should be caught and dismissed. Since conda 4.3, noarch-only repos have been supported (https://github.com/conda/conda/issues/1391). In other words, line 40 should be replaced with a for loop that either checks for file existence or wraps collecting the json in a try/catch block.
