### ISSUE TITLE
Named default channels

### ISSUE THREAD

**Issue by jakirkham** [conda/constructor#42]
Currently one can provide the option `conda_default_channels` in the `construct.yaml` file to specify what channels the installer will call `defaults` and pre-include. However, it would be nice if the default channels were not lumped into one channel called `defaults`. For instance, it would be nice to create an installer where the canonical channels in `defaults` would be included as `defaults` then `conda-forge` would be included as a default channel, but still listed as `conda-forge`. This is essential for debugging of installs to not get too hairy. If this is already provided that is awesome, please help me find the relevant info to get started using this.

If this is not already provided, I would like to propose the follow syntax. To name a channel or group of channels that is preincluded a dictionary should be used. This doesn't break the normal listing usage shown below.

``` yaml
conda_default_channels:
   - http://repo.continuum.io/pkgs/free
```

Simply one adds the dictionary key to the channel they want to name. With the example below, there is a pre-included `conda-forge` channel that pulls from `http://conda.anaconda.org/conda-forge` and a `defaults` channel that pulls from `http://repo.continuum.io/pkgs/free`.

``` yaml
conda_default_channels:
   - conda-forge: http://conda.anaconda.org/conda-forge
   - http://repo.continuum.io/pkgs/free
```

If there are multiple channels that share a name in that dictionary, a list should be used. In this case, the `conda-forge` channel pulls from `http://conda.anaconda.org/conda-forge` and the fictitious `http://conda.anaconda.org/conda-forge-test`. 

``` yaml
conda_default_channels:
   - conda-forge:
      - http://conda.anaconda.org/conda-forge
      - http://conda.anaconda.org/conda-forge-test
   - http://repo.continuum.io/pkgs/free
```

Providing this functionality of named default channels allows one to ensure the user still gets packages from the expected locations, but avoids potential issues where the definition of what is pre-included in those channels (e.g. `defaults`) breaks with existing user expectation. It also helps one to debug when packages coming from to channels that conflict with each other.

cc @loriab @msarahan
