### ISSUE TITLE
Feature:  allow configuration for pinning packages

### ISSUE THREAD

**Issue by bkreider** [conda/constructor#464]
A nice feature would be to allow for pinning of packages on install.  Right now this needs to run as a post-install script, but allowing packages to be pinned automatically would be really nice to protect the root environment.

```
pinned:
  - [matchspec]
```

**Comment by ericpre** [comment]
This is possible using the [`condarc` parameter](https://github.com/conda/constructor/blob/master/CONSTRUCT.md#condarc):
https://docs.conda.io/projects/conda/en/latest/configuration.html#conda-configuration

```yaml
condarc:
  channels:
    - conda-forge
  pinned_packages:
    - python=3.8
```
