### ISSUE TITLE
Modify the name of the constructed environment?

### ISSUE THREAD

**Issue by hoechenberger** [conda/constructor#471]
Hello,

after activating an environment installed using an installer that was created with `constructor`, the command line prompt displays the environment name `base`. I've tried constructing from an existing environment with a different name, and from an environment file that had `name` set. However, this didn't change anything.

I'm worried that having the prompt state that the `base` environment is active could be irritating to our users (in fact, it also confused me when working with this environment – I thought I had selected the wrong environment and needed to check again!)

Is there a way to change the name of the created environment?

Thank you very much!

Richard

**Comment by hoechenberger** [comment]
I am using the following workaround now:

In `construct.yaml`, I've added:

```yaml
condarc:
  channels:
    - conda-forge
  default_channels:
    - conda-forge
  env_prompt: (my-custom-prefix)   # <- !!!
```

This will add `(my-custom-prefix)` as a prompt prefix upon environment activation.
