### ISSUE TITLE
Bug: version of python reported as 3.1 in the windows wizard

### ISSUE THREAD

**Issue by grbd** [conda/constructor#495]
Hi,
I've been working on a constructor script for use with cadquery

  * https://github.com/CadQuery/cadquery/pull/1000

we've noticed that in the windows installer it mentions python 3.1 for some reason instead of 3.10
maybe the string is getting truncated
``` yaml
name: cadquery
version: master
installer_type: all

license_file: ../../LICENSE

# Don't add to the system Path
initialize_by_default: false
# Don't set as the default python
register_python_default: false

channels:
  - http://repo.anaconda.com/pkgs/main/
  - conda-forge
  - cadquery

write_condarc: true
conda_default_channels:
  - conda-forge
  - cadquery

specs:
  - python 3.10*
  - conda
# Occt is too big to bundle so install during post_install instead
#  - cadquery

post_install: post-install.sh           # [unix]
post_install: post-install.bat          # [win]
```
