### ISSUE TITLE
Use packages from pip in the environment file

### ISSUE THREAD

**Issue by vigneshmanick** [conda/constructor#515]
My `construct.yaml`  is as follows

```yaml
name: TestPackage
version: 0.0.1
channels:
  - http://repo.anaconda.com/pkgs/main/

environment_file: environment.yml

license_file: EULA.txt
```

and the `environment.yml`  is as follows

```yaml

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - conda
  - pip:
    - black
    - somepackage-0.0.1-cp38-cp38-linux_x86_64.whl
```

when `construct .`  is called,  i see that the output shows that the packages from pip are being installed in the temporary environment but **don't** show up in the created installer  (both `black` and `somepackage` )

Any suggestions on what might be happening here?

Thanks!
