### ISSUE TITLE
failed create environment on ubuntu docker

### ISSUE THREAD

**Issue by divastar** [conda/constructor#672]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

so I have started a new ubuntu docker 
installed miniconda
and run :

```
$ conda create -n constructor constructor
$ conda activate constructor
$ constructor -h
```

then `constructor .`
the construct.yaml is:

```yaml
name: Me
version: "1"
channels:
  - pytorch
  - http://repo.continuum.io/pkgs/main/
  - https://conda.anaconda.org/ilan
  - defaults
  - conda-forge
specs:
  - python 3.10.*
  - conda
  - mkl  # [win]
  - numpy
  - scipy
  - pandas
  - notebook
  - matplotlib
  - lighttpd  # [unix]
  - pytorch
  - cudatoolkit
  - opencv
  - Pillow
  - matplotlib
  - pyyaml
  - requests
  - scipy
  - torchvision
  - tqdm
  - pandas
  - seaborn
  - psutil
  - easyocr
  - editdistance
  - hydra-core
  - imageio
  - imutils
  - ninja
  - multiprocess
  - omegaconf
  - onnx
  - onnxruntime
  - openpyxl
  - packaging
  - pipreqs
  - prettytable
  - protobuf
  - psutil
  - pyparsing
  - six
  - imageio
  - scikit-learn
  - tensorboard
  - timm
  - yacs
  - tqdm
  - timm
  - setuptools
  - transformers
  - typing-extensions
  - regex
  - protobuf
  
license_file: EULA.txt
```

  the environment was not created the resulting Me-1-Linux-x86_64.sh is always 1.1 G

### Conda Info

```shell
active environment : constructor
    active env location : /root/miniconda3/envs/constructor
            shell level : 2
       user config file : /root/.condarc
 populated config files :
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=5.10.16.3=0
                          __unix=0=0
       base environment : /root/miniconda3  (writable)
      conda av data dir : /root/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /root/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /root/miniconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.10.10 Linux/5.10.16.3-microsoft-standard-WSL2 ubuntu/22.04.2 glibc/2.35
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
nothing
```

### Conda list

```shell
# packages in environment at /root/miniconda3/envs/constructor:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
brotlipy                  0.7.0           py311h5eee18b_1002    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2023.01.10           h06a4308_0    defaults
certifi                   2022.12.7       py311h06a4308_0    defaults
cffi                      1.15.1          py311h5eee18b_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     22.11.1         py311h06a4308_5    defaults
conda-package-handling    2.0.2           py311h06a4308_0    defaults
conda-package-streaming   0.7.0           py311h06a4308_0    defaults
conda-standalone          22.11.1              h06a4308_1    defaults
constructor               3.4.3           py311h06a4308_1    defaults
cryptography              39.0.1          py311h9ce1e76_0    defaults
freetype                  2.12.1               h4a9f257_0    defaults
giflib                    5.2.1                h5eee18b_3    defaults
idna                      3.4             py311h06a4308_0    defaults
jpeg                      9e                   h5eee18b_1    defaults
lcms2                     2.12                 h3be6417_0    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
lerc                      3.0                  h295c915_0    defaults
libdeflate                1.17                 h5eee18b_0    defaults
libffi                    3.4.4                h6a678d5_0    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libpng                    1.6.39               h5eee18b_0    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libtiff                   4.5.0                h6a678d5_2    defaults
libuuid                   1.41.5               h5eee18b_0    defaults
libwebp                   1.2.4                h11a3e52_1    defaults
libwebp-base              1.2.4                h5eee18b_1    defaults
lz4-c                     1.9.4                h6a678d5_0    defaults
ncurses                   6.4                  h6a678d5_0    defaults
openssl                   1.1.1t               h7f8727e_0    defaults
pillow                    9.4.0           py311h6a678d5_0    defaults
pip                       23.0.1          py311h06a4308_0    defaults
pluggy                    1.0.0           py311h06a4308_1    defaults
pycosat                   0.6.4           py311h5eee18b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.0.0          py311h06a4308_0    defaults
pysocks                   1.7.1           py311h06a4308_0    defaults
python                    3.11.3               h7a1cb2a_0    defaults
readline                  8.2                  h5eee18b_0    defaults
requests                  2.29.0          py311h06a4308_0    defaults
ruamel.yaml               0.17.21         py311h5eee18b_0    defaults
ruamel_yaml               0.17.21         py311h5eee18b_0    defaults
setuptools                66.0.0          py311h06a4308_0    defaults
sqlite                    3.41.2               h5eee18b_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
toolz                     0.12.0          py311h06a4308_0    defaults
tqdm                      4.65.0          py311h92b7b1e_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.15         py311h06a4308_0    defaults
wheel                     0.38.4          py311h06a4308_0    defaults
xz                        5.4.2                h5eee18b_0    defaults
zlib                      1.2.13               h5eee18b_0    defaults
zstandard                 0.19.0          py311h5eee18b_0    defaults
zstd                      1.5.5                hc292b87_0    defaults
```
