### ISSUE TITLE
How to supress a message related to scikit-learn?

### ISSUE THREAD

**Issue by namannimmo10** [conda/constructor#773]
I get this message while I build (and run) an installer with conda constructor,

```
Preparing transaction: done
Executing transaction: |
/

    Installed package of scikit-learn can be accelerated using scikit-learn-intelex.
    More details are available here: https://intel.github.io/scikit-learn-intelex

    For example:

        $ conda install scikit-learn-intelex
        $ python -m sklearnex my_application.py



done
installation finished.
Thank you for installing dials-installer!
```

`construct.yaml` is as simple as:

```yaml
name: dials-installer
version: "3.18.0"
channels:
  - defaults
installer_type: all
environment_file: environment.yml
initialize_by_default: true

```

Apparently this message about `scikit-learn` is [common](https://github.com/search?q=%22More+details+are+available+here%3A+https%3A%2F%2Fintel.github.io%2Fscikit-learn-intelex%22&type=code).
Is there a way to suppress it? It is misleading the users of this installer.
Should I pass a post installation script or is there a better workaround? Thanks!
